version: '{build}'
skip_non_tags: true
image: Visual Studio 2017
clone_depth: 1
init:
- ps: git config --global core.autocrlf true
environment:
  MODULE_NAME: {MODULE NAME HERE}
  REPOSITORY_DIR: $(APPVEYOR_BUILD_FOLDER)
  DEPENDENCIES: $(APPVEYOR_BUILD_FOLDER)/dependencies
  GARRYSMOD_COMMON: $(APPVEYOR_BUILD_FOLDER)/dependencies/garrysmod_common
  SOURCE_SDK: $(APPVEYOR_BUILD_FOLDER)/dependencies/sourcesdk-minimal
  PREMAKE5_URL: https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-windows.zip
  PREMAKE5_EXECUTABLE: premake5.exe
  PREMAKE5: $(APPVEYOR_BUILD_FOLDER)/dependencies/windows/premake-core/premake5.exe
  BUILD_SCRIPT: $(APPVEYOR_BUILD_FOLDER)/dependencies/garrysmod_common/build/build.ps1
  GARRYSMOD_COMMON_REPOSITORY: https://github.com/danielga/garrysmod_common.git
  BOOTSTRAP_URL: https://raw.githubusercontent.com/danielga/garrysmod_common/master/build/bootstrap.ps1
  PROJECT_OS: windows
  TARGET_OS: win32
  COMPILER_PLATFORM: vs2017
install:
- ps: 'Invoke-Expression ((New-Object System.Net.WebClient).DownloadString("$env:BOOTSTRAP_URL"))'
cache:
- $(APPVEYOR_BUILD_FOLDER)/dependencies/
build_script:
- ps: '& "$env:BUILD_SCRIPT"'
test: off
artifacts:
- path: projects/$(PROJECT_OS)/$(COMPILER_PLATFORM)/release/gmsv_$(MODULE_NAME)_$(TARGET_OS).dll
  name: gmsv_$(MODULE_NAME)_$(TARGET_OS).dll
- path: projects/$(PROJECT_OS)/$(COMPILER_PLATFORM)/release/gmcl_$(MODULE_NAME)_$(TARGET_OS).dll
  name: gmcl_$(MODULE_NAME)_$(TARGET_OS).dll
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: {ENCRYPTED API KEY FOR APPVEYOR HERE https://ci.appveyor.com/tools/encrypt}
  artifact: projects/$(PROJECT_OS)/$(COMPILER_PLATFORM)/release/gmsv_$(MODULE_NAME)_$(TARGET_OS).dll,projects/$(PROJECT_OS)/$(COMPILER_PLATFORM)/release/gmcl_$(MODULE_NAME)_$(TARGET_OS).dll
  force_update: true
