language: cpp
if: tag IS present
git:
  depth: 1
env:
  global:
    - MODULE_NAME="{MODULE NAME HERE}"
      REPOSITORY_DIR="$TRAVIS_BUILD_DIR"
      DEPENDENCIES="$TRAVIS_BUILD_DIR/dependencies"
      GARRYSMOD_COMMON="$TRAVIS_BUILD_DIR/dependencies/garrysmod_common"
      SOURCE_SDK="$TRAVIS_BUILD_DIR/dependencies/sourcesdk-minimal"
      PREMAKE5="$TRAVIS_BUILD_DIR/dependencies/windows/premake-core/premake5.exe"
      BUILD_SCRIPT="$TRAVIS_BUILD_DIR/dependencies/garrysmod_common/build/build.sh"
      GARRYSMOD_COMMON_REPOSITORY="https://github.com/danielga/garrysmod_common.git"
      BOOTSTRAP_URL="https://raw.githubusercontent.com/danielga/garrysmod_common/master/build/bootstrap.sh"
      TARGET_OS="$TRAVIS_OS_NAME"
      COMPILER_PLATFORM=gmake
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - linux-libc-dev:i386
            - g++-8-multilib
      env:
        - PREMAKE5="$TRAVIS_BUILD_DIR/dependencies/linux/premake-core/premake5"
          PROJECT_OS=linux
          PREMAKE5_URL="https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-linux.tar.gz"
      before_install:
        - export CC=gcc-8
          export CXX=g++-8
    - os: osx
      osx_image: xcode9.4
      env:
        - PREMAKE5="$TRAVIS_BUILD_DIR/dependencies/macosx/premake-core/premake5"
          PROJECT_OS=macosx
          PREMAKE5_URL="https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-macosx.tar.gz"
cache:
  directories:
    - "$TRAVIS_BUILD_DIR/dependencies"
install: "curl -s -L \"$BOOTSTRAP_URL\" | bash"
script: "$BUILD_SCRIPT"
deploy:
  provider: releases
  skip_cleanup: true
  file:
    - "${TRAVIS_BUILD_DIR}/projects/${PROJECT_OS}/${COMPILER_PLATFORM}/release/gmsv_${MODULE_NAME}_${TARGET_OS}.dll"
    - "${TRAVIS_BUILD_DIR}/projects/${PROJECT_OS}/${COMPILER_PLATFORM}/release/gmcl_${MODULE_NAME}_${TARGET_OS}.dll"
  on:
    tags: true
  api_key:
    secure: {ENCRYPTED API KEY FOR TRAVIS-CI HERE https://docs.travis-ci.com/user/encryption-keys}
